### ISSUE TITLE
不能生成生成配置文件和 Migration 文件？

### ISSUE THREAD

**Issue by jaynlive** [qinmingyuan/rails_log#3]
不支持使用 rails g rails_log:install自动安装配置文件和 Migration 文件，那这些文件不是得自己生成了？

**Comment by qinmingyuan** [comment]
migration：engine有个统一的迁移的方法：`rake xxx_engine:install:migrations`, 你运行下`rake -T`就会发现。
config：Rails 自带的 config模块，可以自己在initializers文件夹下新建一个文件。然后以如下格式。
RailsLog.configure do |config|
  config.xxx = xxx
end
则会覆盖engine里的默认配置。

**Comment by jaynlive** [comment]
嗯嗯，为何不在ruby china上开个帖子，已使用华顺的exception-track，个人觉得你这个做得不错，打算换你这个试试哈。

**Comment by qinmingyuan** [comment]
感谢你的认可，我会尽快完善下文档，并去除一些依赖。
